package model;
// Generated Sep 2, 2017 3:19:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aranzman generated by hbm2java
 */
public class Aranzman  implements java.io.Serializable {


     private Integer idRezervacije;
     private Putnik putnik;
     private String sifraRezervacije;
     private double cenaAranzmana;
     private Set<RezervisanaSoba> rezervisanaSobas = new HashSet<RezervisanaSoba>(0);

    public Aranzman() {
    }

	
    public Aranzman(Putnik putnik, String sifraRezervacije, double cenaAranzmana) {
        this.putnik = putnik;
        this.sifraRezervacije = sifraRezervacije;
        this.cenaAranzmana = cenaAranzmana;
    }
    public Aranzman(Putnik putnik, String sifraRezervacije, double cenaAranzmana, Set<RezervisanaSoba> rezervisanaSobas) {
       this.putnik = putnik;
       this.sifraRezervacije = sifraRezervacije;
       this.cenaAranzmana = cenaAranzmana;
       this.rezervisanaSobas = rezervisanaSobas;
    }
   
    public Integer getIdRezervacije() {
        return this.idRezervacije;
    }
    
    public void setIdRezervacije(Integer idRezervacije) {
        this.idRezervacije = idRezervacije;
    }
    public Putnik getPutnik() {
        return this.putnik;
    }
    
    public void setPutnik(Putnik putnik) {
        this.putnik = putnik;
    }
    public String getSifraRezervacije() {
        return this.sifraRezervacije;
    }
    
    public void setSifraRezervacije(String sifraRezervacije) {
        this.sifraRezervacije = sifraRezervacije;
    }
    public double getCenaAranzmana() {
        return this.cenaAranzmana;
    }
    
    public void setCenaAranzmana(double cenaAranzmana) {
        this.cenaAranzmana = cenaAranzmana;
    }
    public Set<RezervisanaSoba> getRezervisanaSobas() {
        return this.rezervisanaSobas;
    }
    
    public void setRezervisanaSobas(Set<RezervisanaSoba> rezervisanaSobas) {
        this.rezervisanaSobas = rezervisanaSobas;
    }




}


