package model;
// Generated Sep 2, 2017 3:19:43 PM by Hibernate Tools 4.3.1



/**
 * CenaSobe generated by hbm2java
 */
public class CenaSobe  implements java.io.Serializable {


     private CenaSobeId id;
     private Hotel hotel;
     private TipSobe tipSobe;
     private double cenaPoNocenju;

    public CenaSobe() {
    }

    public CenaSobe(CenaSobeId id, Hotel hotel, TipSobe tipSobe, double cenaPoNocenju) {
       this.id = id;
       this.hotel = hotel;
       this.tipSobe = tipSobe;
       this.cenaPoNocenju = cenaPoNocenju;
    }
   
    public CenaSobeId getId() {
        return this.id;
    }
    
    public void setId(CenaSobeId id) {
        this.id = id;
    }
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }
    public TipSobe getTipSobe() {
        return this.tipSobe;
    }
    
    public void setTipSobe(TipSobe tipSobe) {
        this.tipSobe = tipSobe;
    }
    public double getCenaPoNocenju() {
        return this.cenaPoNocenju;
    }
    
    public void setCenaPoNocenju(double cenaPoNocenju) {
        this.cenaPoNocenju = cenaPoNocenju;
    }




}


