package model;
// Generated Sep 2, 2017 3:19:43 PM by Hibernate Tools 4.3.1



/**
 * CenaSobeId generated by hbm2java
 */
public class CenaSobeId  implements java.io.Serializable {


     private int idHotela;
     private int idTipaSobe;

    public CenaSobeId() {
    }

    public CenaSobeId(int idHotela, int idTipaSobe) {
       this.idHotela = idHotela;
       this.idTipaSobe = idTipaSobe;
    }
   
    public int getIdHotela() {
        return this.idHotela;
    }
    
    public void setIdHotela(int idHotela) {
        this.idHotela = idHotela;
    }
    public int getIdTipaSobe() {
        return this.idTipaSobe;
    }
    
    public void setIdTipaSobe(int idTipaSobe) {
        this.idTipaSobe = idTipaSobe;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CenaSobeId) ) return false;
		 CenaSobeId castOther = ( CenaSobeId ) other; 
         
		 return (this.getIdHotela()==castOther.getIdHotela())
 && (this.getIdTipaSobe()==castOther.getIdTipaSobe());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdHotela();
         result = 37 * result + this.getIdTipaSobe();
         return result;
   }   


}


