package model;
// Generated Sep 2, 2017 3:19:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Destinacija generated by hbm2java
 */
public class Destinacija  implements java.io.Serializable {


     private Integer idDestinacije;
     private Drzava drzava;
     private String imeDestinacije;
     private String opisDestinacije;
     private Set<Hotel> hotels = new HashSet<Hotel>(0);
     private Set<Transport> transports = new HashSet<Transport>(0);

    public Destinacija() {
    }

	
    public Destinacija(Drzava drzava, String imeDestinacije, String opisDestinacije) {
        this.drzava = drzava;
        this.imeDestinacije = imeDestinacije;
        this.opisDestinacije = opisDestinacije;
    }
    public Destinacija(Drzava drzava, String imeDestinacije, String opisDestinacije, Set<Hotel> hotels, Set<Transport> transports) {
       this.drzava = drzava;
       this.imeDestinacije = imeDestinacije;
       this.opisDestinacije = opisDestinacije;
       this.hotels = hotels;
       this.transports = transports;
    }
   
    public Integer getIdDestinacije() {
        return this.idDestinacije;
    }
    
    public void setIdDestinacije(Integer idDestinacije) {
        this.idDestinacije = idDestinacije;
    }
    public Drzava getDrzava() {
        return this.drzava;
    }
    
    public void setDrzava(Drzava drzava) {
        this.drzava = drzava;
    }
    public String getImeDestinacije() {
        return this.imeDestinacije;
    }
    
    public void setImeDestinacije(String imeDestinacije) {
        this.imeDestinacije = imeDestinacije;
    }
    public String getOpisDestinacije() {
        return this.opisDestinacije;
    }
    
    public void setOpisDestinacije(String opisDestinacije) {
        this.opisDestinacije = opisDestinacije;
    }
    public Set<Hotel> getHotels() {
        return this.hotels;
    }
    
    public void setHotels(Set<Hotel> hotels) {
        this.hotels = hotels;
    }
    public Set<Transport> getTransports() {
        return this.transports;
    }
    
    public void setTransports(Set<Transport> transports) {
        this.transports = transports;
    }




}


