package model;
// Generated Sep 2, 2017 3:19:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Drzava generated by hbm2java
 */
public class Drzava  implements java.io.Serializable {


     private Integer idDrzave;
     private String imeDrzave;
     private Set<Destinacija> destinacijas = new HashSet<Destinacija>(0);

    public Drzava() {
    }

	
    public Drzava(String imeDrzave) {
        this.imeDrzave = imeDrzave;
    }
    public Drzava(String imeDrzave, Set<Destinacija> destinacijas) {
       this.imeDrzave = imeDrzave;
       this.destinacijas = destinacijas;
    }
   
    public Integer getIdDrzave() {
        return this.idDrzave;
    }
    
    public void setIdDrzave(Integer idDrzave) {
        this.idDrzave = idDrzave;
    }
    public String getImeDrzave() {
        return this.imeDrzave;
    }
    
    public void setImeDrzave(String imeDrzave) {
        this.imeDrzave = imeDrzave;
    }
    public Set<Destinacija> getDestinacijas() {
        return this.destinacijas;
    }
    
    public void setDestinacijas(Set<Destinacija> destinacijas) {
        this.destinacijas = destinacijas;
    }




}


