package model;
// Generated Sep 2, 2017 3:19:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PrevoznoSredstvo generated by hbm2java
 */
public class PrevoznoSredstvo  implements java.io.Serializable {


     private Integer idPrevoza;
     private String nacinPrevoza;
     private Set<Transport> transports = new HashSet<Transport>(0);

    public PrevoznoSredstvo() {
    }

	
    public PrevoznoSredstvo(String nacinPrevoza) {
        this.nacinPrevoza = nacinPrevoza;
    }
    public PrevoznoSredstvo(String nacinPrevoza, Set<Transport> transports) {
       this.nacinPrevoza = nacinPrevoza;
       this.transports = transports;
    }
   
    public Integer getIdPrevoza() {
        return this.idPrevoza;
    }
    
    public void setIdPrevoza(Integer idPrevoza) {
        this.idPrevoza = idPrevoza;
    }
    public String getNacinPrevoza() {
        return this.nacinPrevoza;
    }
    
    public void setNacinPrevoza(String nacinPrevoza) {
        this.nacinPrevoza = nacinPrevoza;
    }
    public Set<Transport> getTransports() {
        return this.transports;
    }
    
    public void setTransports(Set<Transport> transports) {
        this.transports = transports;
    }




}


