package model;
// Generated Sep 2, 2017 3:19:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Putnik generated by hbm2java
 */
public class Putnik  implements java.io.Serializable {


     private Integer idPutnika;
     private KreditnaKartica kreditnaKartica;
     private String brojPasosa;
     private String imeIPrezimePutnika;
     private String kontaktTelefon;
     private String email;
     private Set<Aranzman> aranzmans = new HashSet<Aranzman>(0);

    public Putnik() {
    }

	
    public Putnik(KreditnaKartica kreditnaKartica, String brojPasosa, String imeIPrezimePutnika, String kontaktTelefon, String email) {
        this.kreditnaKartica = kreditnaKartica;
        this.brojPasosa = brojPasosa;
        this.imeIPrezimePutnika = imeIPrezimePutnika;
        this.kontaktTelefon = kontaktTelefon;
        this.email = email;
    }
    public Putnik(KreditnaKartica kreditnaKartica, String brojPasosa, String imeIPrezimePutnika, String kontaktTelefon, String email, Set<Aranzman> aranzmans) {
       this.kreditnaKartica = kreditnaKartica;
       this.brojPasosa = brojPasosa;
       this.imeIPrezimePutnika = imeIPrezimePutnika;
       this.kontaktTelefon = kontaktTelefon;
       this.email = email;
       this.aranzmans = aranzmans;
    }
   
    public Integer getIdPutnika() {
        return this.idPutnika;
    }
    
    public void setIdPutnika(Integer idPutnika) {
        this.idPutnika = idPutnika;
    }
    public KreditnaKartica getKreditnaKartica() {
        return this.kreditnaKartica;
    }
    
    public void setKreditnaKartica(KreditnaKartica kreditnaKartica) {
        this.kreditnaKartica = kreditnaKartica;
    }
    public String getBrojPasosa() {
        return this.brojPasosa;
    }
    
    public void setBrojPasosa(String brojPasosa) {
        this.brojPasosa = brojPasosa;
    }
    public String getImeIPrezimePutnika() {
        return this.imeIPrezimePutnika;
    }
    
    public void setImeIPrezimePutnika(String imeIPrezimePutnika) {
        this.imeIPrezimePutnika = imeIPrezimePutnika;
    }
    public String getKontaktTelefon() {
        return this.kontaktTelefon;
    }
    
    public void setKontaktTelefon(String kontaktTelefon) {
        this.kontaktTelefon = kontaktTelefon;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Aranzman> getAranzmans() {
        return this.aranzmans;
    }
    
    public void setAranzmans(Set<Aranzman> aranzmans) {
        this.aranzmans = aranzmans;
    }




}


