package model;
// Generated Sep 2, 2017 3:19:43 PM by Hibernate Tools 4.3.1



/**
 * RezervisanaSoba generated by hbm2java
 */
public class RezervisanaSoba  implements java.io.Serializable {


     private RezervisanaSobaId id;
     private Aranzman aranzman;
     private Soba soba;
     private String pocetakRezervacije;
     private String krajRezervacije;

    public RezervisanaSoba() {
    }

	
    public RezervisanaSoba(RezervisanaSobaId id, Aranzman aranzman, Soba soba) {
        this.id = id;
        this.aranzman = aranzman;
        this.soba = soba;
    }
    public RezervisanaSoba(RezervisanaSobaId id, Aranzman aranzman, Soba soba, String pocetakRezervacije, String krajRezervacije) {
       this.id = id;
       this.aranzman = aranzman;
       this.soba = soba;
       this.pocetakRezervacije = pocetakRezervacije;
       this.krajRezervacije = krajRezervacije;
    }
   
    public RezervisanaSobaId getId() {
        return this.id;
    }
    
    public void setId(RezervisanaSobaId id) {
        this.id = id;
    }
    public Aranzman getAranzman() {
        return this.aranzman;
    }
    
    public void setAranzman(Aranzman aranzman) {
        this.aranzman = aranzman;
    }
    public Soba getSoba() {
        return this.soba;
    }
    
    public void setSoba(Soba soba) {
        this.soba = soba;
    }
    public String getPocetakRezervacije() {
        return this.pocetakRezervacije;
    }
    
    public void setPocetakRezervacije(String pocetakRezervacije) {
        this.pocetakRezervacije = pocetakRezervacije;
    }
    public String getKrajRezervacije() {
        return this.krajRezervacije;
    }
    
    public void setKrajRezervacije(String krajRezervacije) {
        this.krajRezervacije = krajRezervacije;
    }




}


