package model;
// Generated Sep 2, 2017 3:19:43 PM by Hibernate Tools 4.3.1



/**
 * RezervisanaSobaId generated by hbm2java
 */
public class RezervisanaSobaId  implements java.io.Serializable {


     private int idSobe;
     private int idRezervacije;

    public RezervisanaSobaId() {
    }

    public RezervisanaSobaId(int idSobe, int idRezervacije) {
       this.idSobe = idSobe;
       this.idRezervacije = idRezervacije;
    }
   
    public int getIdSobe() {
        return this.idSobe;
    }
    
    public void setIdSobe(int idSobe) {
        this.idSobe = idSobe;
    }
    public int getIdRezervacije() {
        return this.idRezervacije;
    }
    
    public void setIdRezervacije(int idRezervacije) {
        this.idRezervacije = idRezervacije;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RezervisanaSobaId) ) return false;
		 RezervisanaSobaId castOther = ( RezervisanaSobaId ) other; 
         
		 return (this.getIdSobe()==castOther.getIdSobe())
 && (this.getIdRezervacije()==castOther.getIdRezervacije());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdSobe();
         result = 37 * result + this.getIdRezervacije();
         return result;
   }   


}


