package model;
// Generated Sep 2, 2017 3:19:43 PM by Hibernate Tools 4.3.1



/**
 * Slika generated by hbm2java
 */
public class Slika  implements java.io.Serializable {


     private Integer idSlike;
     private Hotel hotel;
     private String putanjaSlike;

    public Slika() {
    }

    public Slika(Hotel hotel, String putanjaSlike) {
       this.hotel = hotel;
       this.putanjaSlike = putanjaSlike;
    }
   
    public Integer getIdSlike() {
        return this.idSlike;
    }
    
    public void setIdSlike(Integer idSlike) {
        this.idSlike = idSlike;
    }
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }
    public String getPutanjaSlike() {
        return this.putanjaSlike;
    }
    
    public void setPutanjaSlike(String putanjaSlike) {
        this.putanjaSlike = putanjaSlike;
    }




}


