package model;
// Generated Sep 2, 2017 3:19:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Soba generated by hbm2java
 */
public class Soba  implements java.io.Serializable {


     private Integer idSobe;
     private Hotel hotel;
     private TipSobe tipSobe;
     private String brojSobe;
     private Set<RezervisanaSoba> rezervisanaSobas = new HashSet<RezervisanaSoba>(0);

    public Soba() {
    }

	
    public Soba(Hotel hotel, TipSobe tipSobe, String brojSobe) {
        this.hotel = hotel;
        this.tipSobe = tipSobe;
        this.brojSobe = brojSobe;
    }
    public Soba(Hotel hotel, TipSobe tipSobe, String brojSobe, Set<RezervisanaSoba> rezervisanaSobas) {
       this.hotel = hotel;
       this.tipSobe = tipSobe;
       this.brojSobe = brojSobe;
       this.rezervisanaSobas = rezervisanaSobas;
    }
   
    public Integer getIdSobe() {
        return this.idSobe;
    }
    
    public void setIdSobe(Integer idSobe) {
        this.idSobe = idSobe;
    }
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }
    public TipSobe getTipSobe() {
        return this.tipSobe;
    }
    
    public void setTipSobe(TipSobe tipSobe) {
        this.tipSobe = tipSobe;
    }
    public String getBrojSobe() {
        return this.brojSobe;
    }
    
    public void setBrojSobe(String brojSobe) {
        this.brojSobe = brojSobe;
    }
    public Set<RezervisanaSoba> getRezervisanaSobas() {
        return this.rezervisanaSobas;
    }
    
    public void setRezervisanaSobas(Set<RezervisanaSoba> rezervisanaSobas) {
        this.rezervisanaSobas = rezervisanaSobas;
    }




}


