package model;
// Generated Sep 2, 2017 3:19:43 PM by Hibernate Tools 4.3.1



/**
 * Transport generated by hbm2java
 */
public class Transport  implements java.io.Serializable {


     private TransportId id;
     private Destinacija destinacija;
     private PrevoznoSredstvo prevoznoSredstvo;
     private double cenaTransporta;

    public Transport() {
    }

    public Transport(TransportId id, Destinacija destinacija, PrevoznoSredstvo prevoznoSredstvo, double cenaTransporta) {
       this.id = id;
       this.destinacija = destinacija;
       this.prevoznoSredstvo = prevoznoSredstvo;
       this.cenaTransporta = cenaTransporta;
    }
   
    public TransportId getId() {
        return this.id;
    }
    
    public void setId(TransportId id) {
        this.id = id;
    }
    public Destinacija getDestinacija() {
        return this.destinacija;
    }
    
    public void setDestinacija(Destinacija destinacija) {
        this.destinacija = destinacija;
    }
    public PrevoznoSredstvo getPrevoznoSredstvo() {
        return this.prevoznoSredstvo;
    }
    
    public void setPrevoznoSredstvo(PrevoznoSredstvo prevoznoSredstvo) {
        this.prevoznoSredstvo = prevoznoSredstvo;
    }
    public double getCenaTransporta() {
        return this.cenaTransporta;
    }
    
    public void setCenaTransporta(double cenaTransporta) {
        this.cenaTransporta = cenaTransporta;
    }




}


